import { Bar } from "react-chartjs-2";
import React, { useCallback, useEffect, useState } from "react";
import { firestore } from "../components/firebase";
import Select from "react-dropdown-select";
import { sortMonths } from "../utils/helper";
import { COMPANY_OPTIONS } from "../utils/constants";

const BarChart = () => {
  // labels represents x-axis and values represent y-axis
  const [labels, setLabels] = useState([]);
  const [values, setValues] = useState([]);

  const [company, setCompany] = useState("Google");

  const options = COMPANY_OPTIONS;

  const state = {
    labels: labels,
    datasets: [
      {
        label: `Revenue (${company})`,
        backgroundColor: "#4ab2d1",
        borderColor: "white",
        borderWidth: 1,
        color: "white",
        data: values,
      },
    ],
  };

  const fetchData = useCallback(() => {
    firestore
      .collection("/companies")
      .doc(company)
      .get()
      .then((doc) => {
        const data = doc.data();

        const monthRevenue = sortMonths(data.month);

        // converting revenue value of company for each month from string to int
        const valuArr = [];
        Object.values(monthRevenue).forEach((element) => {
          valuArr.push(parseInt(element.replace(/,/g, "")));
        });

        // set the hook values for labels and values
        setLabels(Object.keys(monthRevenue));
        setValues(valuArr);
      });
  }, [company]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return (
    <div>
      <h2 className="sub-header">
        Below visualization represents revenue of each month generated by a
        company.
      </h2>
      <div className="dropdown">
        <Select
          options={options}
          onChange={(value) => {
            setCompany(value[0].value);
          }}
        />
      </div>
      <Bar
        data={state}
        options={{
          title: {
            display: true,
            text: "Revenue per month",
            fontSize: 20,
            fontColor: "#474646",
            position: "bottom",
            fontFamily: "Roboto",
          },
          legend: {
            display: true,
            position: "chartArea",
          },
        }}
      />
    </div>
  );
};

export default BarChart;
