import React, { useCallback, useEffect, useState } from "react";
import { Line } from "react-chartjs-2";
import Select from "react-dropdown-select";

import { firestore } from "../components/firebase";
import { MONTHS, COUNTRY_OPTIONS } from "../utils/constants";
import { getTotalRevenuePerMonth } from "../utils/helper";

const LineChart = () => {
  const [country1, setCountry1] = useState("India");
  const [country2, setCountry2] = useState("USA");

  const [revenueData1, setRevenueData1] = useState([]);
  const [revenueData2, setRevenueData2] = useState([]);

  const options = COUNTRY_OPTIONS;

  const state = {
    labels: MONTHS,
    datasets: [
      {
        label: country1,
        fill: false,
        lineTension: 0,
        backgroundColor: "rgba(75,192,192,1)",
        borderColor: "#efa656",
        borderWidth: 2,
        data: revenueData1,
      },
      {
        label: country2,
        fill: false,
        lineTension: 0,
        backgroundColor: "rgba(75,192,192,1)",
        borderColor: "#5e8ecf",
        borderWidth: 1,
        data: revenueData2,
      },
    ],
  };

  const fetchData = useCallback(() => {
    firestore
      .collection("companies")
      .where("Country", "==", country1)
      .get()
      .then((querySnapshot) => {
        const data = querySnapshot.docs.map((doc) => doc.data());
        // const id = querySnapshot.docs.map((doc) => doc.id);
        const revenueDataArray = getTotalRevenuePerMonth(data);
        setRevenueData1(revenueDataArray);
      });

    firestore
      .collection("companies")
      .where("Country", "==", country2)
      .get()
      .then((querySnapshot) => {
        const data = querySnapshot.docs.map((doc) => doc.data());
        // const id = querySnapshot.docs.map((doc) => doc.id);
        const revenueDataArray = getTotalRevenuePerMonth(data);
        setRevenueData2(revenueDataArray);
      });
  }, [country1, country2]);

  useEffect(() => {
    fetchData();
  }, [fetchData]);

  return (
    <div>
      <h2 className="sub-header">
        Below visualization represents comparison of revenue generated by
        companies for each month belongs to a country.
      </h2>
      <div className="two-dropdown">
        <div className="dropdown-width">
          <Select
            options={options}
            onChange={(value) => {
              setCountry1(value[0].value);
            }}
          />
        </div>
        <div className="dropdown-width">
          <Select
            options={options}
            onChange={(value) => {
              setCountry2(value[0].value);
            }}
          />
        </div>
      </div>

      <Line
        data={state}
        options={{
          title: {
            display: true,
            text: "Comparison of revenues",
            fontSize: 24,
            fontColor: "white",
          },
          legend: {
            display: true,
            position: "right",
          },
        }}
      />
    </div>
  );
};

export default LineChart;
